### PR TITLE
Corrected some minor typos

### PR DESCRIPTION
**Pull request by anthonyanjorin**
- language-related typo
- parameter name of sameIpAddress

### CODE REVIEW

**Comment by anthonyanjorin** [comment]
- Did you author 100% of the content?:  **Yes**
- Do you have the rights to contribute this content to VIATRA?:  **Yes**
- Is the contribution under the Eclipse Public License?:  **Yes**

I do hope these answers hold for all future commits I might make :)

**Comment by ujhelyiz** [comment]
Thanks again for the contribution; if you provide a "blank" provision for the possible future commits, we can link back here in case of issues. :)

**Comment by anthonyanjorin** [comment]
Ok - here is a blank provision for all my future commits to this repo:
- I shall author 100% of all contents I commit
- I have the rights to contribute such future content
- All my future contributions to this repo will be under the Eclipse Public License

Cheers,
Tony

**Comment by ujhelyiz** [comment]
Thank you again very much for your interest and cooperation.

**Pull request merged**
